parameters:
  vmImage: ''
  service_connection_github: '' 

jobs:
- job: Tag for Release

  pool:
    vmImage: ${{ parameters.vmImage }}

  variables:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

  steps:

  - template: install.dotnet-global-tools.workaround.yml
  - template: install-and-run-gitversion.yml

  - powershell: |
      Write-Host "##vso[task.setvariable variable=Endjin_Repository_Name]$Env:BUILD_REPOSITORY_NAME"
    displayName: 'Set Custom Environment Variables'

  - task: GitHubTag@1
    displayName: 'Tag Git'
    inputs:
      githubEndpoint: $(service_connection_github)
      repositoryName: $(Endjin_Repository_Name)
      commmit: 'Release v$(GitVersion.MajorMinorPatch)'
      tag: '$(GitVersion.MajorMinorPatch)'